version: "3"
services:
  ircbot:
    build: .
    volumes:
      - ./src:/usr/src/app
    environment:
      - SERVER=irc.freenode.net
      - SERVER_PORT=6667
      - BOT_NICKNAME=sedsbot
      - ALLOWED_NICKS=seds,
      - LOGFILE=ircbot.log
